"""initial_schema

Revision ID: d053498dcad0
Revises: 
Create Date: 2026-01-30 14:40:37.848151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd053498dcad0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create graph_storages table
    op.create_table(
        'graph_storages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('work_dir', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create app_settings table with foreign key to graph_storages
    op.create_table(
        'app_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('value', sa.String(length=100), nullable=True),
        sa.Column('storage_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['storage_id'], ['graph_storages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    op.drop_table('graph_storages')
    # ### end Alembic commands ###
